### ISSUE TITLE
unable to install 0.8 through pip in python 3.5

### ISSUE THREAD

**Issue by cecemel** [benosteen/pairtree#4]
Output during install

>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/ff/ys76d3zn0msd4l9xhtkcj5s40000gn/T/pip-build-a12_x64k/pairtree/setup.py", line 1, in <module>
>         from ez_setup import use_setuptools
>     ImportError: No module named 'ez_setup'

**Comment by benosteen** [comment]
Hi,

Sorry about that! Try the 0.8.1 version I've just uploaded (removes the
legacy ez_setup part)

**Comment by cecemel** [comment]
thx, seems to install now!
